// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Test",
    "version": "1"
  },
  "paths": {
    "/customers/create": {
      "post": {
        "summary": "createCustomer",
        "description": "",
        "tags": [
          "Clientes"
        ],
        "operationId": "createCustomer.post.customers/create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/IReadCustomer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/customers/read/{form}/{parameter}": {
      "get": {
        "summary": "readCustomer",
        "description": "",
        "tags": [
          "Clientes"
        ],
        "operationId": "readCustomer.get.customers/read/{form}/{parameter}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ICreateCustomer"
            }
          },
          {
            "name": "form",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "parameter",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/customers/update/{form}/{parameter}": {
      "put": {
        "summary": "updateCustomer",
        "description": "",
        "tags": [
          "Clientes"
        ],
        "operationId": "updateCustomer.put.customers/update/{form}/{parameter}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/IUpdateCustomer"
            }
          },
          {
            "name": "form",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "parameter",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ICreateCustomer": {
      "properties": {
        "name": {
          "title": "ICreateCustomer.name",
          "type": "string"
        },
        "email": {
          "title": "ICreateCustomer.email",
          "type": "string"
        },
        "birthdate": {
          "title": "ICreateCustomer.birthdate",
          "type": "string"
        },
        "cellphone": {
          "title": "ICreateCustomer.cellphone",
          "type": "string"
        },
        "active": {
          "enum": [
            1,
            0
          ],
          "title": "ICreateCustomer.active",
          "type": "number"
        }
      },
      "required": [
        "name",
        "email",
        "birthdate",
        "cellphone",
        "active"
      ],
      "additionalProperties": false,
      "title": "ICreateCustomer",
      "type": "object"
    },
    "IReadCustomer": {
      "properties": {
        "form": {
          "title": "IReadCustomer.form",
          "type": "string"
        },
        "parameter": {
          "title": "IReadCustomer.parameter",
          "type": "string"
        }
      },
      "required": [
        "form",
        "parameter"
      ],
      "additionalProperties": false,
      "title": "IReadCustomer",
      "type": "object"
    },
    "IUpdateCustomer": {
      "properties": {
        "name": {
          "title": "IUpdateCustomer.name",
          "type": "string"
        },
        "email": {
          "title": "IUpdateCustomer.email",
          "type": "string"
        },
        "birthdate": {
          "title": "IUpdateCustomer.birthdate",
          "type": "string"
        },
        "cellphone": {
          "title": "IUpdateCustomer.cellphone",
          "type": "string"
        },
        "active": {
          "enum": [
            1,
            0
          ],
          "title": "IUpdateCustomer.active",
          "type": "number"
        },
        "form": {
          "title": "IUpdateCustomer.form",
          "type": "string"
        },
        "parameter": {
          "title": "IUpdateCustomer.parameter",
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "birthdate",
        "cellphone",
        "active",
        "form",
        "parameter"
      ],
      "additionalProperties": false,
      "title": "IUpdateCustomer",
      "type": "object"
    }
  },
  "securityDefinitions": {
    "Authorization": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "basePath": "/dev",
  "host": "gez89o4ob2.execute-api.us-east-1.amazonaws.com/dev",
  "schemes": [
    "https"
  ]
};